### ISSUE TITLE
Automatically disconnecting after every command increases processing time

### ISSUE THREAD

**Issue by murrant** [epiecs/phpmiko#3]
https://github.com/epiecs/phpmiko/commit/8fdddf0d78d50d7cdc534924f3d256fa5cd79604 broke my code flow:
Connect.
*fetch ipv4 data
*fetch ipv6 data
formulate new commands
*send ipv4 config changes
*send ipv6 config changes
disconnect

It now disconnects after every command (the asterisks), setting $deviceConnection to null and throwing a null exception when the next command is run. Reconnecting after every command adds significant time.

Options to fix:

1. create a command sequence class that disconnects on destruct
2. force the user to manually disconnect
3. create a config option "disconnect after commands"

**Comment by epiecs** [comment]
Hi,

Good point. Maybe the best way to implement this then would be via `__destruct()`. Then it will behave more like using `with` in Python.

Allowing the using to manually disconnect should also always be available.

I will try and post a fix later today.

Kr, Gregory

**Comment by epiecs** [comment]
Hi,

This should be fixed now :)

https://github.com/epiecs/phpmiko/releases/tag/v1.1.3

The release should be picked up by packagist shortly.

Kr, Gregory
